Repository home-assistant/wheels-custom-integrations, pull requests merged in 2021-01, with the labels that each got.

#224 Add Elasticsearch integration
  components/elasticsearch.json
Labels: cla-signed

#226 EMSC RSS added
  components/emscrss.json
Labels: cla-signed

#225 Add Fully Kiosk Browser custom component
  components/fullykiosk.json
Labels: cla-signed

#227 Transferred HomeWizard Energy integration
  components/homewizard_energy.json
Labels: cla-signed

#229 Added Optus Integration
  components/optus.json
Labels: cla-signed

#228 Add xiaomi_miio_philipslight
  components/xiaomi_miio_philipslight.json
Labels: cla-signed

#230 Add miio_yeelink
  components/miio_yeelink.json
Labels: cla-signed

#231 GitHub Actions > Azure pipelines
  .github/workflows/ci.yaml
  .github/workflows/wheels.yml
  azure-pipelines-ci.yml
  azure-pipelines-wheels.yml
  components/hacs.json
Labels: cla-signed

#171 Add new integration mitemp_bt2
  components/mitemp_bt2.json
Labels: cla-signed, hacktoberfest-accepted

#214 custom integration for Helsinki Regional Transport
  components/hslhrt.json
Labels: cla-signed

#196 Add nsw_rural_fire_service_fire_danger integration
  components/nsw_rural_fire_service_fire_danger.json
Labels: cla-signed

#232 Fix broken CI and add pin check
  .github/workflows/ci.yaml
  .github/workflows/wheels.yml
  components/hacs.json
Labels: cla-signed

#233 Use single
  .github/workflows/wheels.yml
Labels: cla-signed

#237 Add xiaomi_miot
  components/xiaomi_miot.json
Labels: cla-signed

#234 Add XiaomiGateway3 integration
  components/xiaomi_gateway3.json
Labels: cla-signed

#238 Fix path for elasticsearch
  components/elasticsearch.json
Labels: cla-signed

#239 Ignore duplicates
  .github/workflows/wheels.yml
Labels: cla-signed

#241 Updated [HomeWizard Energy] integration due to GitHub account rename
  components/homewizard_energy.json
Labels: cla-signed

#242 add iCal Sensor
  components/ics.json
Labels: cla-signed

#240 Add Easee EV charger
  components/easee_hass
Labels: cla-signed

#243 Rename easee_hass to easee_hass.json
  components/easee_hass.json
Labels: cla-signed

#249 Create moat_temp_hum_ble.json
  components/moat_temp_hum_ble.json
Labels: cla-signed

#248 Create beoplay
  components/beoplay
Labels: cla-signed

#247 Add danfoss_ally.json
  components/danfoss_ally.json
Labels: cla-signed

#253 Add viomise.json
  components/viomise.json
Labels: cla-signed

#252 Add Sagemcom F@st
  components/sagemcom_fast.json
Labels: cla-signed

#254 Add bosch_shc
  components/bosch_shc.json
Labels: cla-signed

#244 Create vivint.json
  components/vivint.json
Labels: cla-signed

#255 Add xiaomi_miot_raw
  components/xiaomi_miot_raw.json
Labels: cla-signed

#256 feat(components/aws_codepipeline.json): added aws codepipeline
  components/aws_codepipeline.json
Labels: cla-signed

#258 Custom component provider for teufel_raumfeld
  components/teufel_raumfeld.json
Labels: cla-needed

#260 Update manifest in accordance to changes in teufel_raumfeld repository
  components/teufel_raumfeld.json
Labels: cla-needed
